#This configuration resource decalaration file is provisions an auto mode VPC
resources:
- name: custom-vpc
  type: compute.v1.network
  properties:
    routingConfig:
      routingMode: REGIONAL
    autoCreateSubnetworks: false

#Command line for deploying a a VPC as IaC => Commented
#gcloud deployment-manager deployments create my-deployment --config=config.yaml --description="My deployment"


# This configuration resource decalaration file provisions a subnet
- name: subnet-custom
  type: compute.v1.subnetwork
  properties:
    ipCidrRange: 10.130.0.0/20
    network: $(ref.custom-vpc.selfLink)
    region: us-central1

# Command line for deploying a subnet as IaC => Commented
# gcloud deployment-manager deployments create my-deployment --config=config.yaml --description="My deployment"
# gcloud deployment-manager deployments create my-deployment --config=Subnet1-Custom-VPC.yaml 